nick: ProductManager
channel: '#product_development'
host: localhost
port: 6667
tls: false
model: llama3.2:3b
temperature: 0.35
prompt: ../../prompts/product_development/ProductManager.md
llm_node: 10.209.1.96
reply_to_all: true
